---
title: "Survey Text Analysis"
author: "Chris Selig"
date: "10/22/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    echo = F,
    warning = F,
    message = F
    )
```

```{r load libraries}
# Workhorse: data manipulation, plotting
library(tidyverse)
library(janitor)

# Read in data
library(readxl)

# Text specific packages
library(tidytext)
library(stopwords)

# Visualization packages
library(ggthemes)
```


```{r load data}
raw_data <- read_excel("../00_data/survey_text_responses.xlsx",sheet = "Survey_responses")
keyword <- read_excel("../00_data/keywords.xlsx")
```

```{r source scripts}
source("../01_scripts/01_data_processing.R")
```

```{r unigrams data processing}
unigram_tidy_data <- raw_data %>% 
    clean_column_names_function() %>% 
    tokenize_data_function() %>% 
    remove_stop_words_function()
```

## Visualize Most Common Words

```{r set theme for plots}
# Set theme
theme_set(theme_tufte())
```

```{r unigram visual}
unigram_tidy_data %>% 
    count(question, word) %>%
    group_by(question) %>%
    arrange(desc(n)) %>%
    top_n(10) %>% 
    ungroup() %>% 
    mutate(
        question = as.factor(question),
        word = reorder_within(word, n, question)
    ) %>% 
    ggplot(aes(word,n)) +
    geom_bar(stat = 'identity',aes(fill = n), fill = '#A2AAB0') +
    coord_flip() +
    geom_text(aes(label = n), size = 3, hjust = 1.4, color = 'black') +
    facet_wrap(~question,scales = "free") +
    scale_x_reordered() +
    labs(
        x = '',
        y = ''
    ) +
    theme(
        plot.title = element_text(size = 14, family = "memphis",color = '#4C586F', face = 'bold'),
        plot.subtitle = element_text(hjust = 0.01, size = 11,family = "ArnoProLightDisplay"),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        legend.position = "none"
    )
```


